Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
10.12.217.240 - - [18/Sep/2025 16:26:06] "GET / HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:06] "GET /images/residential-complex.jpg HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:07] "GET /js/vercel-analytics.js HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:07] "GET /js/config.js HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:07] "GET /js/main.js HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:07] "GET /js/visitor-lookup.js HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:07] "GET /css/style.css HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:07] "GET /css/alter5-colors.css HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:07] "GET /js/debug-visitor-tracking.js HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:07] code 501, message Unsupported method ('POST')
10.12.217.240 - - [18/Sep/2025 16:26:07] "POST /api/analytics HTTP/1.1" 501 -
10.12.217.240 - - [18/Sep/2025 16:26:07] "HEAD /documents/Financial-Model-Valdebebas.xlsx HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:07] "HEAD /documents/Project-ZURICH-Teaser-ENG.docx HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:07] "HEAD /documents/Project-Ederson-TermSheet-ENG.docx HTTP/1.1" 200 -
10.12.217.240 - - [18/Sep/2025 16:26:08] code 404, message File not found
10.12.217.240 - - [18/Sep/2025 16:26:08] "GET /favicon.ico HTTP/1.1" 404 -
10.12.217.240 - - [18/Sep/2025 16:26:12] code 501, message Unsupported method ('POST')
10.12.217.240 - - [18/Sep/2025 16:26:12] "POST /api/analytics HTTP/1.1" 501 -
10.12.217.240 - - [18/Sep/2025 16:26:13] code 501, message Unsupported method ('POST')
10.12.217.240 - - [18/Sep/2025 16:26:13] "POST /api/analytics HTTP/1.1" 501 -
10.12.217.240 - - [18/Sep/2025 16:32:21] "GET /project-zurich-equity.html HTTP/1.1" 200 -
10.12.112.36 - - [19/Sep/2025 10:04:40] code 501, message Unsupported method ('POST')
10.12.112.36 - - [19/Sep/2025 10:04:40] "HEAD /documents/Project-ZURICH-Teaser-ENG.docx HTTP/1.1" 200 -
10.12.112.36 - - [19/Sep/2025 10:04:40] "POST /api/analytics HTTP/1.1" 501 -
10.12.112.36 - - [19/Sep/2025 10:04:40] "HEAD /documents/Project-Ederson-TermSheet-ENG.docx HTTP/1.1" 200 -
10.12.112.36 - - [19/Sep/2025 10:04:40] "HEAD /documents/Financial-Model-Valdebebas.xlsx HTTP/1.1" 200 -
10.12.112.36 - - [19/Sep/2025 10:04:43] code 501, message Unsupported method ('POST')
10.12.112.36 - - [19/Sep/2025 10:04:43] "POST /api/analytics HTTP/1.1" 501 -
10.12.112.36 - - [19/Sep/2025 10:04:45] code 501, message Unsupported method ('POST')
10.12.112.36 - - [19/Sep/2025 10:04:45] "POST /api/analytics HTTP/1.1" 501 -
10.12.112.36 - - [19/Sep/2025 10:04:45] code 501, message Unsupported method ('POST')
10.12.112.36 - - [19/Sep/2025 10:04:45] "POST /api/analytics HTTP/1.1" 501 -
10.12.112.36 - - [19/Sep/2025 10:04:45] code 501, message Unsupported method ('POST')
10.12.112.36 - - [19/Sep/2025 10:04:45] "POST /api/analytics HTTP/1.1" 501 -
10.12.112.36 - - [19/Sep/2025 10:04:56] code 501, message Unsupported method ('POST')
10.12.112.36 - - [19/Sep/2025 10:04:56] "POST /api/analytics HTTP/1.1" 501 -
10.12.112.36 - - [19/Sep/2025 10:05:00] code 501, message Unsupported method ('POST')
10.12.112.36 - - [19/Sep/2025 10:05:00] "POST /api/analytics HTTP/1.1" 501 -
10.12.112.36 - - [19/Sep/2025 10:13:05] code 501, message Unsupported method ('POST')
10.12.112.36 - - [19/Sep/2025 10:13:05] "POST /api/analytics HTTP/1.1" 501 -
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
10.12.134.98 - - [20/Sep/2025 09:12:16] "GET /equity_investment.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:12:16] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:12:16] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 09:12:16] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 09:12:31] "GET /verification-complete.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:12:31] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:12:31] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 09:12:31] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 09:12:46] "GET /index.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:12:46] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 09:12:46] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 09:14:24] "GET /demo-funcional.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:14:24] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 09:14:24] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 09:38:23] "GET /index.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:38:24] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 09:38:24] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 09:38:29] "GET /admin-simple.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:38:36] "GET /admin-docs.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:44:30] "GET /equity_investment.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:44:31] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 09:44:46] "GET /equity_investment.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:05:56] "GET /test-existing-buttons.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:05:56] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:05:56] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 10:05:56] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 10:06:09] "GET /equity_investment.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:06:09] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:06:09] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 10:06:09] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 10:09:53] "GET /admin-docs.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:10:34] "GET /equity_investment.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:10:34] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:10:46] "GET /equity_investment_en.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:10:53] "GET /index.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:20:16] "GET /equity_investment.html HTTP/1.1" 304 -
10.12.134.98 - - [20/Sep/2025 10:20:16] "GET /js/document-manager.js HTTP/1.1" 304 -
10.12.134.98 - - [20/Sep/2025 10:20:19] "GET /equity_investment.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:25:28] "GET /admin-docs.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:25:28] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:25:28] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 10:25:28] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 10:25:55] "GET /admin-docs.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:25:55] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:25:55] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 10:25:55] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 10:26:50] "GET /test-full-workflow.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:26:50] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:26:51] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 10:26:51] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 10:27:03] "GET /equity_investment.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:27:03] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:27:03] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 10:27:03] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 10:35:27] "GET /admin-docs.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:35:27] "GET /js/document-manager.js HTTP/1.1" 304 -
10.12.134.98 - - [20/Sep/2025 10:36:06] "GET /equity_investment.html HTTP/1.1" 304 -
10.12.134.98 - - [20/Sep/2025 10:36:30] "GET /admin-docs.html HTTP/1.1" 304 -
10.12.134.98 - - [20/Sep/2025 10:36:51] "GET /equity_investment.html HTTP/1.1" 304 -
10.12.134.98 - - [20/Sep/2025 10:38:38] "GET /debug-modelo-financiero.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:38:38] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:38:38] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 10:38:38] "GET /favicon.ico HTTP/1.1" 404 -
10.12.134.98 - - [20/Sep/2025 10:39:15] "GET /test-modelo-simple.html HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:39:15] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.134.98 - - [20/Sep/2025 10:39:15] code 404, message File not found
10.12.134.98 - - [20/Sep/2025 10:39:15] "GET /favicon.ico HTTP/1.1" 404 -
10.12.21.150 - - [22/Sep/2025 10:54:49] "GET /senior_financing_en.html HTTP/1.1" 200 -
10.12.21.150 - - [22/Sep/2025 10:54:49] "GET /images/project-zurich-new.jpg HTTP/1.1" 200 -
10.12.21.150 - - [22/Sep/2025 10:54:49] code 404, message File not found
10.12.21.150 - - [22/Sep/2025 10:54:49] "GET /favicon.ico HTTP/1.1" 404 -
10.12.21.150 - - [22/Sep/2025 10:54:53] "GET /equity_investment_en.html HTTP/1.1" 200 -
10.12.21.150 - - [22/Sep/2025 10:54:53] "GET /js/document-manager.js HTTP/1.1" 200 -
10.12.21.150 - - [22/Sep/2025 10:54:56] "GET /project-zurich-equity.html HTTP/1.1" 200 -
10.12.21.150 - - [22/Sep/2025 10:56:54] "GET /senior_financing_en.html HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/simple_server.py", line 13, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
10.12.21.150 - - [22/Sep/2025 10:59:15] "GET /senior_financing_en.html HTTP/1.1" 200 -
10.12.21.150 - - [22/Sep/2025 10:59:28] code 404, message File not found
10.12.21.150 - - [22/Sep/2025 10:59:28] "GET /senior_financing.html HTTP/1.1" 404 -
10.12.21.150 - - [22/Sep/2025 10:59:34] code 404, message File not found
10.12.21.150 - - [22/Sep/2025 10:59:34] "GET /senior_financing_es.html HTTP/1.1" 404 -
10.12.21.150 - - [22/Sep/2025 10:59:38] "GET / HTTP/1.1" 200 -
10.12.21.150 - - [22/Sep/2025 10:59:42] "GET /project-zurich-equity.html HTTP/1.1" 200 -
10.12.21.150 - - [22/Sep/2025 11:08:29] "GET /senior_financing_en.html HTTP/1.1" 304 -
10.12.21.150 - - [22/Sep/2025 11:08:29] "GET /images/project-zurich-new.jpg HTTP/1.1" 304 -
